export const ROLLBAR_ACCESS_TOKEN = process.env.EXPO_PUBLIC_ROLLBAR_ACCESS_TOKEN;

export const ROLLBAR_ENV = process.env.EXPO_PUBLIC_ROLLBAR_ENV;

export const MAPBOX_ACCESS_TOKEN = process.env.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN;

export const EARTH_RADIUS_METERS = 6371e3;
